name: rHologramChat
version: '${project.version}'
main: dev.rishon.rhologramchat.Main
api-version: 1.19
authors: [ Rishon ]
description: Async NMS Hologram Chat
website: https://rishon.systems
commands:
  rhologramchat:
    description: Main command for rHologramChat
    aliases: [ rhc, hologramchat ]
    permission: rhologramchat.cmd.use
  selfhologram:
    description: See your own holographic messages
    aliases: [ selfh ]
    permission: rhologramchat.cmd.selfhologram
